import type { MarketplaceItem, Business, User } from "./types"

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: "1",
    title: "Vintage Dining Table",
    price: 150,
    image: "/vintage-dining-table.jpg",
    seller: {
      name: "Michael Chen",
      avatar: "/diverse-user-avatars.png",
      initials: "MC",
      rating: 4.8,
    },
    condition: "Good",
    location: "0.3 miles away",
    description:
      "Beautiful vintage dining table in excellent condition. Solid wood construction with minor wear consistent with age. Seats 6 comfortably. Perfect for family dinners or entertaining guests.",
    images: ["/vintage-dining-table.jpg", "/vintage-chairs.jpg", "/office-chair-side.jpg"],
    category: "Furniture",
    postedDate: "2 days ago",
  },
  {
    id: "2",
    title: "Office Chair",
    price: 75,
    image: "/ergonomic-office-chair.png",
    seller: {
      name: "Sarah Williams",
      avatar: "/diverse-user-avatars.png",
      initials: "SW",
      rating: 4.9,
    },
    condition: "Like New",
    location: "0.5 miles away",
    description: "Ergonomic office chair with lumbar support. Barely used, like new condition.",
    images: ["/ergonomic-office-chair.png"],
    category: "Furniture",
    postedDate: "1 week ago",
  },
  {
    id: "3",
    title: "Anime Art Print",
    price: 25,
    image: "/anime-art.jpg",
    seller: {
      name: "David Kim",
      avatar: "/diverse-user-avatars.png",
      initials: "DK",
      rating: 5.0,
    },
    condition: "New",
    location: "0.8 miles away",
    description: "Limited edition anime art print. Never displayed, mint condition.",
    images: ["/anime-art.jpg", "/anime-art-2.jpg", "/anime-art-3.jpg"],
    category: "Art",
    postedDate: "3 days ago",
  },
]

export const businesses: Business[] = [
  {
    id: "1",
    name: "TechHub Electronics",
    category: "Electronics",
    rating: 4.8,
    reviews: 234,
    distance: "0.2 miles",
    image: "/electronics-store-interior.png",
    logo: "/abstract-tech-logo.png",
    description:
      "Your one-stop shop for all electronics needs. We offer the latest smartphones, laptops, accessories, and more at competitive prices.",
    hours: "Mon-Sat: 9AM-8PM, Sun: 10AM-6PM",
    phone: "(555) 123-4567",
    address: "123 Main St, Your City",
    owner: {
      name: "James Wilson",
      avatar: "/diverse-user-avatars.png",
      initials: "JW",
    },
    catalog: [
      {
        id: "1",
        name: "Wireless Earbuds Pro",
        price: 89.99,
        image: "/wireless-earbuds.png",
        category: "Audio",
        description: "Premium wireless earbuds with active noise cancellation and 24-hour battery life.",
        images: ["/wireless-earbuds.png"],
        inStock: true,
      },
      {
        id: "2",
        name: "Phone Case Collection",
        price: 19.99,
        image: "/colorful-phone-case-display.png",
        category: "Accessories",
        description: "Durable phone cases in various colors and designs. Compatible with all major phone models.",
        images: ["/colorful-phone-case-display.png"],
        inStock: true,
      },
    ],
  },
  {
    id: "2",
    name: "FitLife Gym",
    category: "Fitness",
    rating: 4.9,
    reviews: 456,
    distance: "0.4 miles",
    image: "/gym-interior.png",
    logo: "/fitness-gym-logo.png",
    description: "State-of-the-art fitness facility with personal trainers, group classes, and modern equipment.",
    hours: "Mon-Fri: 5AM-11PM, Sat-Sun: 6AM-10PM",
    phone: "(555) 234-5678",
    address: "456 Fitness Ave, Your City",
    owner: {
      name: "Maria Rodriguez",
      avatar: "/diverse-user-avatars.png",
      initials: "MR",
    },
    catalog: [
      {
        id: "1",
        name: "Monthly Membership",
        price: 49.99,
        image: "/gym-membership-card.jpg",
        category: "Membership",
        description: "Full access to all gym facilities and equipment. Includes free fitness assessment.",
        images: ["/gym-membership-card.jpg"],
        inStock: true,
      },
      {
        id: "2",
        name: "Personal Training (10 sessions)",
        price: 299.99,
        image: "/personal-trainer-session.jpg",
        category: "Training",
        description: "One-on-one training sessions with certified personal trainers. Customized workout plans.",
        images: ["/personal-trainer-session.jpg"],
        inStock: true,
      },
    ],
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    username: "@sarahj",
    avatar: "/diverse-user-avatars.png",
    initials: "SJ",
    bio: "Love exploring local businesses and events!",
    location: "Downtown",
    joinedDate: "January 2024",
    friendsCount: 234,
    isFriend: false,
  },
  {
    id: "2",
    name: "Michael Chen",
    username: "@mchen",
    avatar: "/diverse-user-avatars.png",
    initials: "MC",
    bio: "Furniture enthusiast and DIY lover",
    location: "Westside",
    joinedDate: "March 2024",
    friendsCount: 156,
    isFriend: true,
  },
  {
    id: "3",
    name: "David Kim",
    username: "@dkim",
    avatar: "/diverse-user-avatars.png",
    initials: "DK",
    bio: "Anime collector and artist",
    location: "Eastside",
    joinedDate: "February 2024",
    friendsCount: 89,
    isFriend: false,
  },
]
